env:
  PROJECT_NAME: (zh-cn)refined-prun

name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      
      - uses: pnpm/action-setup@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      
      - run: pnpm install --frozen-lockfile
      
      - name: Build All Platforms
        run: pnpm run package:all

      - name: Create Source Archive
        run: git archive --output (zh-cn)refined-prun-SourceCode.zip HEAD

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            (Chrome)(zh-cn)refined-prun.zip
            (Firefox)(zh-cn)refined-prun.zip
            (Edge)(zh-cn)refined-prun.zip
            (zh-cn)refined-prun-SourceCode.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chrome:
    needs: build
    name: Submit (Chrome)
    environment: Chrome
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build Chrome
        run: pnpm run build:chrome
      - run: npx chrome-webstore-upload-cli@3
        working-directory: dist/chrome
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

  firefox:
    needs: build
    name: Submit (Firefox)
    environment: Firefox
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - name: Build Firefox
        run: pnpm run build:firefox
      - name: Zip source code for AMO
        run: git archive --output source.zip HEAD
      - name: Upload build and source code
        run: npx web-ext@8 sign --channel listed --upload-source-code ../../source.zip
        working-directory: dist/firefox
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
